global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: vaultfs
    metrics_path: /metrics
    static_configs:
      - targets:
          - node1:8001
          - node2:8002
          - node3:8003
        labels:
          cluster: vaultfs-local
